import { router, json, error, requireAuth, requireAdminEmailAllowlist } from '@appdeploy/sdk';
import { db, storage } from '@appdeploy/sdk';
const ADMIN_EMAILS=['dickson@company.test']; const AUTHORISED_EMAILS=['dickson@company.test','omega@company.test'];
type Role='Member'|'Authorised'|'Admin'; const now=()=>new Date().toISOString();
function roleFor(email=''):Role{if(ADMIN_EMAILS.includes(email.toLowerCase()))return'Admin';if(AUTHORISED_EMAILS.includes(email.toLowerCase()))return'Authorised';return'Member'}
function canApply(user:{email?:string},role:Role){return role==='Admin'||AUTHORISED_EMAILS.includes((user.email||'').toLowerCase())}
async function ensureUser(ctx:any){const email=(ctx.user!.email||'').toLowerCase();const listed=await db.list<any>('users',{limit:100});let record=listed.items.find((u:any)=>u.userId===ctx.user!.userId);if(!record){const role=roleFor(email);const[id]=await db.add('users',[{userId:ctx.user!.userId,email,name:ctx.user!.name||email.split('@')[0],role,canMarkApplied:canApply(ctx.user!,role),active:true,createdAt:now()}]);record={id,userId:ctx.user!.userId,email,name:ctx.user!.name||email.split('@')[0],role,canMarkApplied:canApply(ctx.user!,role),active:true}}return record}
async function actor(ctx:any){return ensureUser(ctx)} async function findById<T>(table:string,id:string){const[r]=await db.get<T>(table,[id]);return r?{...(r as any),id}:null} async function log(tenderId:string,ctx:any,action:string,detail?:string){const u=await actor(ctx);await db.add('activity',[{tenderId,actorId:ctx.user!.userId,actorName:u.name,action,detail:detail||'',createdAt:now()}])}
export async function reminderHandler(_event:any){const listed=await db.list<any>('tenders',{limit:200});const users=(await db.list<any>('users',{limit:200})).items;const current=Date.now();for(const tender of listed.items){if(tender.status==='Applied'||tender.status==='Declined')continue;const diff=new Date(tender.deadline).getTime()-current;const days=Math.ceil(diff/86400000);if(![14,7,3,1,0].includes(days)&&diff>=0)continue;const title=diff<0?'Bid overdue':days===0?'Bid due today':`Bid due in ${days} day${days===1?'':'s'}`;const body=`${tender.title} for ${tender.organisation} is ${diff<0?'past its deadline':'approaching its deadline'}.`;const targets=tender.assigneeId?users.filter((u:any)=>u.id===tender.assigneeId):users;for(const u of targets){const existing=await db.list<any>('notifications',{limit:200});const already=existing.items.some((n:any)=>n.tenderId===tender.id&&n.userId===u.userId&&n.kind===`deadline-${days}`&&new Date(n.createdAt).toDateString()===new Date().toDateString());if(!already)await db.add('notifications',[{userId:u.userId,tenderId:tender.id,kind:`deadline-${days}`,title,body,read:false,createdAt:now()}])}}return{statusCode:200}}
export const handler=router({
'GET /api/me':[requireAuth(),async ctx=>{const u=await actor(ctx);return json({user:{id:u.id,userId:u.userId,email:u.email,name:u.name,role:u.role,canMarkApplied:u.canMarkApplied,active:u.active}})}],
'GET /api/tenders':[requireAuth(),async ctx=>{const u=await actor(ctx);const{items}=await db.list<any>('tenders',{limit:200});return json({tenders:items.map((x:any)=>({...x,submittedBy:x.submittedBy||u.id}))})}],
'POST /api/tenders':[requireAuth(),async ctx=>{const u=await actor(ctx);const b=ctx.body as any;if(!b.title||!b.organisation||!b.deadline)return error('Title, organisation and deadline are required.',400);const[id]=await db.add('tenders',[{title:b.title,organisation:b.organisation,reference:b.reference||'',description:b.description||'',deadline:b.deadline,source:b.source||'',url:b.url||'',category:b.category||'Other',status:'New',assigneeId:b.assigneeId||'',submittedBy:u.id,submittedAt:now(),notes:b.notes||''}]);if(!id)return error('Could not create tender.',500);await log(id,ctx,'created the bid');return json({tender:{id,...b,status:'New',submittedBy:u.id,submittedAt:now()}},201)}],
'GET /api/tenders/:id/attachments':[requireAuth(),async ctx=>{const{items}=await db.list<any>('attachments',{limit:200});return json({attachments:items.filter((x:any)=>x.tenderId===ctx.params.id)})}],
'POST /api/tenders/:id/attachments':[requireAuth(),async ctx=>{const u=await actor(ctx);const b=ctx.body as any;if(!b.filename||!b.content)return error('File data is required.',400);if(b.size>800000)return error('File is too large for this upload route. Use a file under 800 KB.',400);const path=`tenders/${ctx.params.id}/${crypto.randomUUID()}-${String(b.filename).replace(/[^a-zA-Z0-9._-]/g,'_')}`;const[ok]=await storage.write([{path,content:b.content,contentType:b.mimeType||'application/octet-stream'}]);if(!ok)return error('File upload failed.',500);const[id]=await db.add('attachments',[{tenderId:ctx.params.id,filename:b.filename,mimeType:b.mimeType||'application/octet-stream',size:b.size||0,path,uploadedBy:u.id,uploadedAt:now()}]);await log(ctx.params.id,ctx,'uploaded an attachment',b.filename);return json({attachment:{id,filename:b.filename}},201)}],
'GET /api/attachments/:id/url':[requireAuth(),async ctx=>{const a=await findById<any>('attachments',ctx.params.id);if(!a)return error('Attachment not found.',404);const[{url}]=await storage.url([a.path]);return json({url})}],
'GET /api/tenders/:id/activity':[requireAuth(),async ctx=>{const{items}=await db.list<any>('activity',{limit:200});return json({activities:items.filter((x:any)=>x.tenderId===ctx.params.id).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())})}],
'PUT /api/tenders/:id':[requireAuth(),async ctx=>{const u=await actor(ctx);if(u.role==='Member')return error('Only authorised users can edit bids.',403);const existing=await findById<any>('tenders',ctx.params.id);if(!existing)return error('Bid not found.',404);const b=ctx.body as any;const next={...existing,status:b.status||existing.status,assigneeId:b.assigneeId??existing.assigneeId};await db.update('tenders',[{id:existing.id,record:next}]);if(next.status!==existing.status)await log(existing.id,ctx,'changed status',`${existing.status} → ${next.status}`);if(next.assigneeId!==existing.assigneeId)await log(existing.id,ctx,'changed the assignee');return json({tender:next})}],
'POST /api/tenders/:id/apply':[requireAuth(),async ctx=>{const u=await actor(ctx);if(!u.canMarkApplied)return error('You are not authorised to mark bids as Applied.',403);const existing=await findById<any>('tenders',ctx.params.id);if(!existing)return error('Bid not found.',404);const b=ctx.body as any;const appliedAt=now();const next={...existing,status:'Applied',appliedBy:u.id,appliedAt,submissionReference:b.submissionReference||''};await db.update('tenders',[{id:existing.id,record:next}]);await log(existing.id,ctx,'marked the bid Applied',b.submissionReference||'');return json({tender:next})}],
'POST /api/tenders/:id/decline':[requireAuth(),async ctx=>{const u=await actor(ctx);if(!u.canMarkApplied)return error('You are not authorised to decline bids.',403);const existing=await findById<any>('tenders',ctx.params.id);if(!existing)return error('Bid not found.',404);const next={...existing,status:'Declined'};await db.update('tenders',[{id:existing.id,record:next}]);await log(existing.id,ctx,'marked the bid Declined');return json({tender:next})}],
'GET /api/notifications':[requireAuth(),async ctx=>{const{items}=await db.list<any>('notifications',{limit:200});return json({notifications:items.filter((n:any)=>n.userId===ctx.user!.userId).sort((a:any,b:any)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())})}],
'POST /api/notifications/:id/read':[requireAuth(),async ctx=>{const n=await findById<any>('notifications',ctx.params.id);if(!n||n.userId!==ctx.user!.userId)return error('Notification not found.',404);await db.update('notifications',[{id:n.id,record:{...n,read:true}}]);return json({ok:true})}],
'GET /api/users':[requireAuth(),requireAdminEmailAllowlist(ADMIN_EMAILS),async()=>{const{items}=await db.list<any>('users',{limit:200});return json({users:items})}],
'PUT /api/users/:id':[requireAuth(),requireAdminEmailAllowlist(ADMIN_EMAILS),async ctx=>{const existing=await findById<any>('users',ctx.params.id);if(!existing)return error('User not found.',404);const b=ctx.body as any;const next={...existing,...(b.role?{role:b.role}:{}),...(typeof b.canMarkApplied==='boolean'?{canMarkApplied:b.canMarkApplied}:{}),...(typeof b.active==='boolean'?{active:b.active}:{})};await db.update('users',[{id:existing.id,record:next}]);return json({user:next})}]
});
